In [1]:
conda install numpy

Solving environment: done

## Package Plan ##

  environment location: /home/abhi/anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2022.10.11 |       h06a4308_0         124 KB
    ------------------------------------------------------------
                                           Total:         124 KB

The following packages will be UPDATED:

  ca-certificates                     2022.07.19-h06a4308_0 --> 2022.10.11-h06a4308_0 None



ca-certificates-2022 | 124 KB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Retrieving notices: ...working... done

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

# Creating a Numpy array

In [3]:
# from list
list1 = [1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [4]:
np.array(list1)

array([1, 2, 3, 4, 5])

In [5]:
matrix1 = [[1,2,3],[4,5,6],[7,8,9]]
matrix1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(matrix1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Methods

# arange
returns evenly spaced values in a given interval

np.arange(start, stop, step)

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# Zeros and Ones

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Identity Matrix
np.eye(number)

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# linspace
returns evenly spaced numbers over a given interval, It is giving 50 numbers by default

np.linspace(start,stop,number)

In [14]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [16]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [17]:
np.linspace(0,20,30)

array([ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069,
        3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655,
        6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241,
       10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828,
       13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414,
       17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ])

# Random

rand(shape)
- Create an array of the given shape and populate it with random samples from a uniform distribution over ``[0, 1)``.

randn(shape)
- Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform

randint(start,stop,step)
- Return random integers from `low` (inclusive) to `high` (exclusive).

In [18]:
np.random.rand(5)

array([0.51741358, 0.66124619, 0.12855245, 0.16727322, 0.03179219])

In [19]:
np.random.rand(5,5)

array([[0.96394789, 0.55875134, 0.80811296, 0.39806649, 0.49326328],
       [0.51001032, 0.69058546, 0.56665649, 0.22664747, 0.74544323],
       [0.42449977, 0.42720541, 0.04672576, 0.02503463, 0.91638026],
       [0.79498816, 0.37276205, 0.18412361, 0.04610436, 0.93518303],
       [0.21941034, 0.1885213 , 0.08168548, 0.37456642, 0.81553116]])

In [20]:
np.random.rand(5,5,5)

array([[[0.92132311, 0.66382007, 0.61130633, 0.80957905, 0.65740864],
        [0.28327838, 0.15322793, 0.35644709, 0.88820089, 0.30453982],
        [0.740724  , 0.3505411 , 0.2276184 , 0.56176923, 0.7994585 ],
        [0.60730944, 0.61114833, 0.83831353, 0.36182057, 0.05323073],
        [0.89587121, 0.7639005 , 0.80080991, 0.11883483, 0.8613639 ]],

       [[0.35154684, 0.69314043, 0.8335839 , 0.08279608, 0.96974183],
        [0.54069871, 0.74806404, 0.59679784, 0.47097715, 0.38619411],
        [0.38702456, 0.90984007, 0.64701333, 0.06270792, 0.64232199],
        [0.59133382, 0.73221766, 0.92754066, 0.03156378, 0.0011072 ],
        [0.33369957, 0.54651799, 0.53596717, 0.97784924, 0.55488695]],

       [[0.35477462, 0.59137875, 0.72279449, 0.15930713, 0.20634229],
        [0.75162165, 0.33089502, 0.50265566, 0.24768874, 0.11937054],
        [0.11721348, 0.98240655, 0.49750624, 0.15639724, 0.87452996],
        [0.55709748, 0.06556996, 0.79572623, 0.94726191, 0.93954373],
        [0.67435

In [21]:
np.random.randn(5)

array([-1.07477634,  0.77266041, -0.00448259, -0.68953232, -1.06962162])

In [22]:
np.random.randn(5,5)

array([[ 0.50904351, -2.13010373, -1.01046713, -0.55616777, -1.32448309],
       [ 0.13760005, -0.72344463,  0.57062593,  0.16119358,  0.51052127],
       [ 0.52117508, -0.90750377,  0.07816159,  1.47500694, -0.23797458],
       [ 0.18051663, -0.44590716,  0.43318013,  0.31378899,  0.1113826 ],
       [ 0.5579648 , -0.43144513,  0.47089961,  0.66366978,  0.68573168]])

In [23]:
np.random.randn(5,5,5)

array([[[-0.47699071,  2.27200727, -0.56442348,  1.92401664,
          2.16913462],
        [-0.17372557,  1.10013968,  1.27154555, -1.48480333,
         -1.77110947],
        [ 1.14946088, -0.55193386,  0.39757745,  0.00719754,
          1.27524167],
        [-0.0559012 , -0.0868451 ,  1.11647071,  0.9432016 ,
         -1.21506571],
        [-0.02642934, -0.95246036, -0.24732332,  0.00975714,
          0.97362964]],

       [[-0.68051474, -0.65803022, -0.42330519, -1.81986737,
         -0.29630116],
        [ 1.37652823, -1.71681575, -0.47129859,  1.45687283,
         -0.36115405],
        [-0.41018488,  2.50164533,  1.0556946 ,  0.25216088,
          0.05095878],
        [ 0.31373303, -1.9191354 , -0.97092853,  0.07865165,
          0.89077711],
        [-0.40196099, -1.48125968,  0.19731121, -0.64134936,
         -0.18588776]],

       [[-0.11228095,  0.25334492,  1.35966256,  0.31343092,
          0.10632392],
        [ 0.78242616, -1.16842302,  0.15758188, -0.33852767,
         -1

In [24]:
np.random.randint(0,5)

0

In [25]:
np.random.randint(0,5,5)

array([0, 2, 3, 2, 1])

# Array attributes and methods

In [26]:
arr1 = np.arange(50)
arr2 = np.random.randint(0,100,20)

In [27]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [28]:
arr2

array([55, 64, 11, 81, 51, 54, 58, 97, 19, 55, 30, 53, 36, 18, 98, 14, 47,
       10, 76, 65])

# Reshape
- Returns an array with the same data in a different shape

In [29]:
arr1.reshape(10,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

# min, max, argmin, argmax

In [30]:
# Getting the maximum value from the array arr1
arr2.max()

98

In [31]:
# argmax is the method which gives us the index of the maximum value in the array
arr2.argmax()

14

In [32]:
# Getting the minimum value from the array arr1
arr2.min()

10

In [33]:
# argmin is the method which gives us the index of the minimum value in the array
arr2.argmin()

17

# Shape
shape is an attribute of the arrays and not a method

In [34]:
# Getting the shape of the array arr1
arr1.shape

(50,)

In [35]:
# Reshaping the array arr1 using reshape method
arr1.reshape(1,50)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49]])

In [36]:
# This shows that the shape of the arr1 after reshaping is 1 rows and 50 column
arr1.reshape(1,50).shape

(1, 50)

In [37]:
# Reshaping the array arr1 using reshape method
arr1.reshape(50,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49]])

In [38]:
# This shows that the shape of the arr1 after reshaping is 50 rows and 1 column
arr1.reshape(50,1).shape

(50, 1)

In [39]:
# The dtype method shows us the data type of the vector
arr1.dtype

dtype('int64')