In [1]:
conda install numpy

Solving environment: done

## Package Plan ##

  environment location: /home/abhi/anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2022.07.19 |       h06a4308_0         124 KB
    certifi-2022.9.24          |   py37h06a4308_0         154 KB
    conda-22.9.0               |   py37h06a4308_0         878 KB
    openssl-1.1.1q             |       h7f8727e_0         2.5 MB
    ------------------------------------------------------------
                                           Total:         3.7 MB

The following packages will be UPDATED:

  ca-certificates                      2022.4.26-h06a4308_0 --> 2022.07.19-h06a4308_0
  certifi                        2022.5.18.1-py37h06a4308_0 --> 2022.9.24-py37h06a4308_0
  conda                               4.13.0-py37h06a4308_0 --> 22.9.0-py37h06a4308_0
  openssl                      

In [1]:
import numpy as np

# Creating a Numpy array

In [2]:
# from list
list1 = [1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [3]:
np.array(list1)

array([1, 2, 3, 4, 5])

In [4]:
matrix1 = [[1,2,3],[4,5,6],[7,8,9]]
matrix1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(matrix1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Methods

# arange
returns evenly spaced values in a given interval

np.arange(start, stop, step)

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# Zeros and Ones

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Identity Matrix
np.eye(number)

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# linspace
returns evenly spaced numbers over a given interval, It is giving 50 numbers by default

np.linspace(start,stop,number)

In [14]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [16]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [18]:
np.linspace(0,20,30)

array([ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069,
        3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655,
        6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241,
       10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828,
       13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414,
       17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ])

# Random

rand(shape)
- Create an array of the given shape and populate it with random samples from a uniform distribution over ``[0, 1)``.

randn(shape)
- Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform

randint(start,stop,step)
- Return random integers from `low` (inclusive) to `high` (exclusive).

In [20]:
np.random.rand(5)

array([0.35418506, 0.54740133, 0.10719507, 0.98798777, 0.85871712])

In [21]:
np.random.rand(5,5)

array([[0.93844557, 0.37411701, 0.67497812, 0.08523061, 0.67701727],
       [0.4486475 , 0.8557146 , 0.26027997, 0.37495518, 0.49958678],
       [0.98818813, 0.80937018, 0.52274153, 0.27255762, 0.47019464],
       [0.37517777, 0.16605338, 0.87629158, 0.41811044, 0.31421651],
       [0.13619814, 0.46871821, 0.22192028, 0.39397458, 0.84156168]])

In [22]:
np.random.rand(5,5,5)

array([[[0.9952629 , 0.37422562, 0.96377842, 0.97533693, 0.75253198],
        [0.32026528, 0.86005329, 0.01050715, 0.75400813, 0.99382903],
        [0.39621715, 0.12304212, 0.81010596, 0.88530042, 0.94346928],
        [0.50430447, 0.45603708, 0.9866525 , 0.92240655, 0.96048328],
        [0.80019833, 0.46719256, 0.86062858, 0.19957245, 0.67836252]],

       [[0.97274954, 0.03168469, 0.67066543, 0.35476599, 0.4097457 ],
        [0.36819623, 0.63525997, 0.51552038, 0.10390085, 0.72212773],
        [0.85651255, 0.53531883, 0.17551987, 0.18909391, 0.24392009],
        [0.23369193, 0.02106833, 0.55672403, 0.17935508, 0.77935565],
        [0.71218717, 0.30798111, 0.4566325 , 0.54300628, 0.97232981]],

       [[0.13930541, 0.3888655 , 0.06989441, 0.8973573 , 0.50547818],
        [0.57869967, 0.55115029, 0.40383624, 0.26402971, 0.66364537],
        [0.48894436, 0.11744442, 0.85888556, 0.38466384, 0.34690192],
        [0.98947428, 0.96692754, 0.94781631, 0.12600726, 0.34054134],
        [0.40301

In [23]:
np.random.randn(5)

array([-0.91505992,  0.5907883 ,  0.95175687,  1.07519649,  1.42671086])

In [24]:
np.random.randn(5,5)

array([[-0.37228371, -1.96687256,  0.31772145, -0.27281315, -0.1105348 ],
       [-0.89206442,  1.5416299 , -1.00923046, -0.53760824, -0.105585  ],
       [-1.38701229,  1.72267162,  1.38812358, -1.32031299, -2.23605206],
       [-0.40181563,  0.69294437,  0.50579442, -0.69083727, -0.85811979],
       [-1.44537359,  0.28877985,  0.04788601,  0.97188945,  1.015584  ]])

In [25]:
np.random.randn(5,5,5)

array([[[ 0.09862253,  1.59764702,  0.32588108,  0.95332262,
         -0.18254624],
        [ 1.23005203, -0.58288639,  1.01600746, -1.56426722,
          1.11641899],
        [ 0.77539031,  0.75373335,  0.66678629, -0.47822614,
         -0.59642159],
        [ 0.62726826, -0.75923457,  1.42379504, -1.32743991,
          0.73159696],
        [-0.8752917 ,  0.2796571 , -0.67355658,  0.92966088,
          0.9806903 ]],

       [[ 0.56192654, -0.70532485, -1.5358149 ,  2.04581832,
          0.70427516],
        [-0.49535993, -0.66365917,  0.76779309,  0.91430426,
          0.02090368],
        [-0.84209346,  0.69545532,  0.53530222, -2.05356184,
         -0.43425187],
        [-0.71901236, -0.65065856, -1.85822225, -0.04731218,
         -0.36324372],
        [ 0.00718394,  0.4306649 , -0.30650539, -0.07831737,
         -0.72898785]],

       [[ 0.52713759,  0.91745848, -1.22335551, -1.00361979,
          0.60698593],
        [-0.50704712, -0.85848814, -0.91812029,  0.32728715,
          0

In [30]:
np.random.randint(0,5)

2

In [31]:
np.random.randint(0,5,5)

array([2, 4, 4, 1, 1])

# Array attributes and methods

In [32]:
arr1 = np.arange(50)
arr2 = np.random.randint(0,100,20)

In [33]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [34]:
arr2

array([ 4, 39, 42, 67, 57, 75, 84, 36, 44, 79, 26, 94, 59, 91, 77, 99,  1,
       74, 15, 26])

# Reshape
- Returns an array with the same data in a different shape

In [36]:
arr1.reshape(10,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

# min, max, argmin, argmax

In [38]:
arr2.max()

99

In [39]:
arr2.argmax()

15

In [40]:
arr2.min()

1

In [41]:
arr2.argmin()

16